# Generated by Django 5.0.6 on 2024-07-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('tuition', models.IntegerField()),
                ('website_link', models.URLField()),
                ('photo_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='university/static/photo/')),
            ],
        ),
    ]
